package com.xm.zeus.db.app.entity;

import com.xm.zeus.db.app.dao.ColleagueDao;
import com.xm.zeus.db.app.dao.ColleagueDeptDao;
import com.xm.zeus.db.app.dao.DaoSession;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "Colleague".
 */
public class Colleague {

    private String uid;
    private String username;
    private String sex;
    private String mobile;
    private String tel;
    private String email;
    private String avatarid;
    private Integer type;
    private Long timestamp;
    private String spelling;
    private String firstletter;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ColleagueDao myDao;

    private List<ColleagueDept> dept;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Colleague() {
    }

    public Colleague(String uid) {
        this.uid = uid;
    }

    public Colleague(String uid, String username, String sex, String mobile, String tel, String email, String avatarid, Integer type, Long timestamp, String spelling, String firstletter) {
        this.uid = uid;
        this.username = username;
        this.sex = sex;
        this.mobile = mobile;
        this.tel = tel;
        this.email = email;
        this.avatarid = avatarid;
        this.type = type;
        this.timestamp = timestamp;
        this.spelling = spelling;
        this.firstletter = firstletter;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getColleagueDao() : null;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAvatarid() {
        return avatarid;
    }

    public void setAvatarid(String avatarid) {
        this.avatarid = avatarid;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public String getSpelling() {
        return spelling;
    }

    public void setSpelling(String spelling) {
        this.spelling = spelling;
    }

    public String getFirstletter() {
        return firstletter;
    }

    public void setFirstletter(String firstletter) {
        this.firstletter = firstletter;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ColleagueDept> getDept() {
        if (dept == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ColleagueDeptDao targetDao = daoSession.getColleagueDeptDao();
            List<ColleagueDept> deptNew = targetDao._queryColleague_Dept(uid);
            synchronized (this) {
                if(dept == null) {
                    dept = deptNew;
                }
            }
        }
        return dept;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetDept() {
        dept = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
