package com.xm.zeus.db.app.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.xm.zeus.db.app.entity.Friend;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "Friend".
*/
public class FriendDao extends AbstractDao<Friend, String> {

    public static final String TABLENAME = "Friend";

    /**
     * Properties of entity Friend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uid = new Property(0, String.class, "uid", true, "UID");
        public final static Property Username = new Property(1, String.class, "username", false, "USERNAME");
        public final static Property Sex = new Property(2, String.class, "sex", false, "SEX");
        public final static Property Mobile = new Property(3, String.class, "mobile", false, "MOBILE");
        public final static Property Tel = new Property(4, String.class, "tel", false, "TEL");
        public final static Property Email = new Property(5, String.class, "email", false, "EMAIL");
        public final static Property Company = new Property(6, String.class, "company", false, "COMPANY");
        public final static Property Dept = new Property(7, String.class, "dept", false, "DEPT");
        public final static Property Post = new Property(8, String.class, "post", false, "POST");
        public final static Property Avatarid = new Property(9, String.class, "avatarid", false, "AVATARID");
        public final static Property Type = new Property(10, Integer.class, "type", false, "TYPE");
        public final static Property Spelling = new Property(11, String.class, "spelling", false, "SPELLING");
        public final static Property FirstLetter = new Property(12, String.class, "firstLetter", false, "FIRST_LETTER");
        public final static Property HeadName = new Property(13, String.class, "headName", false, "HEAD_NAME");
        public final static Property DataType = new Property(14, Integer.class, "dataType", false, "DATA_TYPE");
        public final static Property Timestamp = new Property(15, Long.class, "timestamp", false, "TIMESTAMP");
    };

    private DaoSession daoSession;


    public FriendDao(DaoConfig config) {
        super(config);
    }
    
    public FriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Friend\" (" + //
                "\"UID\" TEXT PRIMARY KEY NOT NULL ," + // 0: uid
                "\"USERNAME\" TEXT," + // 1: username
                "\"SEX\" TEXT," + // 2: sex
                "\"MOBILE\" TEXT," + // 3: mobile
                "\"TEL\" TEXT," + // 4: tel
                "\"EMAIL\" TEXT," + // 5: email
                "\"COMPANY\" TEXT," + // 6: company
                "\"DEPT\" TEXT," + // 7: dept
                "\"POST\" TEXT," + // 8: post
                "\"AVATARID\" TEXT," + // 9: avatarid
                "\"TYPE\" INTEGER," + // 10: type
                "\"SPELLING\" TEXT," + // 11: spelling
                "\"FIRST_LETTER\" TEXT," + // 12: firstLetter
                "\"HEAD_NAME\" TEXT," + // 13: headName
                "\"DATA_TYPE\" INTEGER," + // 14: dataType
                "\"TIMESTAMP\" INTEGER);"); // 15: timestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Friend\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Friend entity) {
        stmt.clearBindings();
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(1, uid);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(3, sex);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(4, mobile);
        }
 
        String tel = entity.getTel();
        if (tel != null) {
            stmt.bindString(5, tel);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(6, email);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(7, company);
        }
 
        String dept = entity.getDept();
        if (dept != null) {
            stmt.bindString(8, dept);
        }
 
        String post = entity.getPost();
        if (post != null) {
            stmt.bindString(9, post);
        }
 
        String avatarid = entity.getAvatarid();
        if (avatarid != null) {
            stmt.bindString(10, avatarid);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(11, type);
        }
 
        String spelling = entity.getSpelling();
        if (spelling != null) {
            stmt.bindString(12, spelling);
        }
 
        String firstLetter = entity.getFirstLetter();
        if (firstLetter != null) {
            stmt.bindString(13, firstLetter);
        }
 
        String headName = entity.getHeadName();
        if (headName != null) {
            stmt.bindString(14, headName);
        }
 
        Integer dataType = entity.getDataType();
        if (dataType != null) {
            stmt.bindLong(15, dataType);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(16, timestamp);
        }
    }

    @Override
    protected void attachEntity(Friend entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Friend readEntity(Cursor cursor, int offset) {
        Friend entity = new Friend( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // uid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // username
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sex
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mobile
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tel
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // email
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // company
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // dept
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // post
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // avatarid
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // type
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // spelling
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // firstLetter
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // headName
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // dataType
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15) // timestamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Friend entity, int offset) {
        entity.setUid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSex(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMobile(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTel(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEmail(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCompany(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDept(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPost(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAvatarid(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setType(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setSpelling(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFirstLetter(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setHeadName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDataType(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setTimestamp(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Friend entity, long rowId) {
        return entity.getUid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Friend entity) {
        if(entity != null) {
            return entity.getUid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
